version: '3.8'

services:
    redis:
      image: redis
      container_name: redis


    frontend:
        image: frontend14
        ports:
            - 5000:5000
        container_name: frontend24


    backend:
        image: backend14
        ports:
            - 8080:8080
        environment:
        - REDIS_HOST=redis
        container_name: backend24
